### ISSUE TITLE
Wires and cables can't be powered with lever

### ISSUE THREAD

**Issue by nikita488** [Commoble/morered#13]
It seems that wires and cables cannot be powered directly with Lever. I'm not sure if it was intended or not.
![image](https://user-images.githubusercontent.com/6237881/111447470-85e3ce80-871e-11eb-8c86-d97c428ade85.png)

**Comment by Commoble** [comment]
It's semi-intentional, but after reconsidering it, it probably should work like the way you expected and I should be able to make it work like that.

In the meantime, you can power levers with wires by attaching the lever to the same block as the wire (the wire will receive the power conducted indirectly through a solid cube).

**Comment by augustoeliezer** [comment]
Or can create his own lever( with wire or stone plate). Having multiple types. Like the delayed levers, or inverse lever (Lever + Not Gate)

**Comment by Commoble** [comment]
Fixed in 1.16.5-2.1.0.1
