### ISSUE TITLE
getting colored network cables or signal to emit strong signal

### ISSUE THREAD

**Issue by DoomSquirter** [Commoble/morered#21]
I read on wiki that they specifically do not emit strong signals.  Is there a block/function that I'm missing if I want them to do precisely this tho?  

Trying to control a 3x3 grid of spawners above the floor I have the cabling.  I want to emit a strong rs signal from below using a colored cable (diff one for each spawner).  

wondering how to go about this with just using more red

**Comment by Commoble** [comment]
There's currently no way to make colored cables transfer strong signals in More Red.

It's intentional that they don't transfer strong signals, so that they can be run along solid blocks without interference from signals being conducted through the blocks.

Regular red alloy wires can transfer strong signals through the block they're attached to.

**Comment by DoomSquirter** [comment]
so, when I was trying this, I could not get the block to emit strong signals probably because of the direction I was going?  One thing that this differs from project red is that if you're snaking a cable up a block, if there's a block above, you can't snake onto that block, thus connecting to it to emit a strong signal.

I can post pictures if that description is lacking.  sorry it took 8 days for me to respond, I forgot about this ticket :(
